### ISSUE TITLE
Should use other (official) logo for DPD Parcelshops 

### ISSUE THREAD

**Issue by Yame-** [Yame-/dpd-parcel#1]
Use this logo instead of old one:
![dpd-parcelshop](https://cloud.githubusercontent.com/assets/4267539/17768991/f0ceb142-6536-11e6-9354-36490537e12b.png)

**Comment by ScratchNoMore** [comment]
Ik heb de plugin geïnstalleerd in WordPress/WooCommerce, waarvoor dank!
De Plugin staat wel in de plugin-lijst, maar ik zie nergens de opties staan. Kun je mij daarin helpen?

Jeroen

**Comment by Yame-** [comment]
Hi Jeroen ( @ScratchNoMore ), 

Normaal gezien vind je de settings onder de "Verzendmethoden/Shipping" tab bij WooCommerce "Instellingen/Settings". 

Kom je hem daar wel tegen? 

Yannick

**Comment by ScratchNoMore** [comment]
Helaas ook niet!

![1](https://cloud.githubusercontent.com/assets/23502244/20351468/3ad44ee6-ac13-11e6-81e3-354208aae7b0.jpg)
![2](https://cloud.githubusercontent.com/assets/23502244/20351469/3aeabe38-ac13-11e6-9ea9-ebdacf8a2f68.jpg)
![3](https://cloud.githubusercontent.com/assets/23502244/20351470/3b055b94-ac13-11e6-8ff9-215ec518ffca.jpg)
