### ISSUE TITLE
QUESTION - DPD Delivery/Shipping Labels

### ISSUE THREAD

**Issue by myfriendmike** [Yame-/dpd-parcel#10]
Please excuse my ignorance but i don't understand what your plugin is designed to do.
I'm reasonable new to Github too!

I've been looking for a plugin to enable the printing of DPD shipment labels 9without all the copying and pasting to DPD app) for our existing Woocommerce store and stumbled on this repo.

Any help appreciated. Mike

**Comment by Yame-** [comment]
Hello @myfriendmike, 

If you have a business account with DPD with credentials you can use this plugin to print shipping labels and have customers select a DPD Parcel Shop when selecting a shipping method. 

If you need more information please don't hesitate to contact me by mail yannick@yame.be
