### ISSUE TITLE
Google Map API issue

### ISSUE THREAD

**Issue by cedriccharles4** [Yame-/dpd-parcel#4]
Hello !

I've installed your plugin and tried to use it on my client website https://gelbopharma.com. I have some problem with the parcel selector map : https://snag.gy/3BXOGx.jpg

I've set an API key...

Thank you in advance !

**Comment by cedriccharles4** [comment]
Hello Yame,

Have you seen my message ? My client want to use DPD but right now it seems impossible... Thank you in advance !

**Comment by Yame-** [comment]
Hi @cedriccharles4,

Could you send me the DPD credentials? I can debug them locally to see if there is a connection problem. Seems that the plugin can't connect to DPD. 

Any chance I could get access to a staging environment to check what's going on?
You can contact me @ yannick@yame.be.
