### ISSUE TITLE
web parcel .be

### ISSUE THREAD

**Issue by flyingcodelabs** [Yame-/dpd-parcel#5]
Werkt deze ook met : https://www.dpdwebparcel.be/ ?

Ik heb de plugin geïnstalleerd, mijn login credentials van bovenstaande website ingegeven.
Google Maps API key en enabled.

Ik krijg vervolgens de mogelijkheid dpd te kiezen bij afrekenen, maar het laden van de map komt niet. 
Blijft grijs 

error in console
![dpd](https://cloud.githubusercontent.com/assets/28501601/25779174/81983910-3312-11e7-967e-a5baeb5f6e5c.png)

Ik hoor graag waar het fout gaat! Dankje!

**Comment by Yame-** [comment]
Hi @flyingcodelabs! 

Bij mijn weten werkt deze spijtig genoeg niet met de dpdwebparcel.be website.
Ik zal het even met IT van DPD opnemen of dit een mogelijkheid is. 

Groeten,
Yannick

**Comment by Yame-** [comment]
Hi @flyingcodelabs. 

DPD heeft me laten weten dat deze systemen, spijtig genoeg, niet aan elkaar gelinkt zijn.

**Comment by flyingcodelabs** [comment]
Hi Yame

Helaas, toch bedankt voor de moeite!
