### ISSUE TITLE
Performance enhancements Google Maps API

### ISSUE THREAD

**Issue by jelkeboonstra** [Yame-/dpd-parcel#9]
Hi Yannick,

Is it necessary to load/enqueue te Google Maps API on every page? For performance related enhancements it would be better to postpone the API call.

Thank you!

Kind regards,
Jelke Boonstra

**Comment by Yame-** [comment]
Hi @jelkeboonstra, 

Thank you for your feedback. I'll tackle this in the next release!

**Comment by Yame-** [comment]
I've enqueued the Google Maps only on the checkout page now. 

Thanks @jelkeboonstra.
